### ISSUE TITLE
Getting an error when trying to start the program

### ISSUE THREAD

**Issue by Dari-OS** [GHaxZ/gee#1]
## I get the following error:

```go
panic: Failed opening '/home/user/.config/gee/engines.json' file: open /home/user/.config/gee/engines.json: no such file or directory

goroutine 1 [running]:
main.loadEngines()
	/home/user/repos/gee/engines.go:57 +0x2e5
main.GetEngines(...)
	/home/user/repos/gee/engines.go:45
main.main()
	/home/user/repos/gee/main.go:31 +0x14d
```

## Steps I took

```bash
 $ git clone https://github.com/GHaxZ/gee.git
    Cloning into 'gee'...
    remote: Enumerating objects: 35, done.
    remote: Counting objects: 100% (35/35), done.
    remote: Compressing objects: 100% (21/21), done.
    remote: Total 35 (delta 16), reused 30 (delta 13), pack-reused 0
    Receiving objects: 100% (35/35), 8.52 KiB | 726.00 KiB/s, done.
    Resolving deltas: 100% (16/16), done.
 $ cd gee/
    /home/user/repos/gee
 $ go build
 $ ./gee 
    panic: Failed opening '/home/user/.config/gee/engines.json' file: open /home/user/.config/gee/engines.json: no such file or     directory

    goroutine 1 [running]:
    main.loadEngines()
    	    /home/user/repos/gee/engines.go:57 +0x2e5
    main.GetEngines(...)
	    /home/user/repos/gee/engines.go:45
    main.main()
	    /home/user/repos/gee/main.go:31 +0x14d
```

## Go version

> **go1.22.5 linux/amd64**

**Comment by GHaxZ** [comment]
Yeah, that's intended, this happens because there is no engines.json config file in the config directory. The program should probably generate a default config.

**Comment by Dari-OS** [comment]
> Yeah, that's intended, this happens because there is no engines.json config file in the config directory. The program should probably generate a default config.

How long would it take to implement this feature?
I really want to use this unique and one-of-a-kind program as an everyday tool.

**Comment by GHaxZ** [comment]
I'm about to delete the repository

**Comment by Dari-OS** [comment]
> I'm about to delete the repository

Your work on this has been invaluable. Before deleting it, please consider its positive impact on many future users that find that tool helpful, just like I did!

**Comment by GHaxZ** [comment]
> > I'm about to delete the repository
> 
> Your work on this has been invaluable. Before deleting it, please consider its positive impact on many future users that find that tool helpful, just like I did!

ok
